name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    working-directory: terraform

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply (Auto Approve)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
