name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Run Terraform
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from GitHub repo
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Terraform (Install Terraform)
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.6.0'  # You can change to a specific version if needed

    # Step 3: Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Step 4: Validate Terraform configuration
    - name: Terraform Validate
      run: terraform validate

    # Step 5: Apply Terraform configuration
    - name: Terraform Apply
      run: terraform apply -auto-approve

    # Step 6 (Optional): Destroy the infrastructure (cleanup)
    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      if: github.event_name == 'push'  # Optional: Only run destroy for push events, not pull requests
